name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  clang-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get CMake 4.1.2
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 4.1.2

      - name: Install Clang 21 and tools
        run: |
          sudo apt update
          sudo apt install -y wget lsb-release software-properties-common
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          sudo apt install -y clang-format-21 clang-tidy-21
          sudo apt install -y libc++-21-dev libc++abi-21-dev
          sudo apt install -y ninja-build

      - name: Set Clang 21 as default
        run: |
          sudo update-alternatives --set clang /usr/lib/llvm-21/bin/clang
          sudo update-alternatives --set clang++ /usr/lib/llvm-21/bin/clang++
          sudo update-alternatives --set clang-format /usr/lib/llvm-21/bin/clang-format
          sudo update-alternatives --set clang-tidy /usr/lib/llvm-21/bin/clang-tidy

      - name: Verify toolchain
        run: |
          clang++ --version
          clang-format --version
          clang-tidy --version
          find / -name std.cppm 2>/dev/null | head -n 5

      - name: Configure
        run: |
          cmake --preset=clang-debug -DCMAKE_CXX_FLAGS="-stdlib=libc++ -nostdinc++ -isystem /usr/lib/llvm-21/share/libc++/v1 -Wall -Wextra -fcolor-diagnostics" -DLIBCXX_INCLUDE_DIR=/usr/lib/llvm-21/share/libc++/v1

      - name: clang-format check
        run: |
          cmake --build --preset=clang-debug --target=format-check

      - name: Build
        run: |
          cmake --build --preset=clang-debug

      - name: clang-tidy
        run: |
          cmake --build --preset=clang-debug --target=tidy
