name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  clang-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Clang 21 and tools
        run: |
          sudo apt update
          sudo apt install -y wget lsb-release software-properties-common
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          which clang-21
          which clang++-21
          clang-format --version
          which clang-tidy-21
          sudo apt install -y ninja-build
          
      - name: Set Clang 21 as default
        run: |
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-21 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-21 100
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-21 100
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-21 100

      - name: Configure
        run: |
          cmake --preset clang-debug

      - name: clang-format check
        run: |
          cmake --build --preset clang-debug --target format-check

      - name: Build
        run: |
          cmake --build --preset clang-debug

      - name: clang-tidy
        run: |
          cmake --build --preset clang-debug --target tidy
