name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch: 
  
jobs:
  clang-ci:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/llvm/ci-ubuntu-24.04:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install CMake 4.1.2
        run: |
          CMAKE_VERSION=4.1.2
          curl -fsSL https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}-linux-x86_64.tar.gz -o cmake.tar.gz
          tar -xzf cmake.tar.gz
          sudo mv cmake-${CMAKE_VERSION}-linux-x86_64 /opt/cmake
          echo "/opt/cmake/bin" >> $GITHUB_PATH

      - name: Add LLVM apt repo (21)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release
          sudo wget https://apt.llvm.org/llvm.sh
          sudo chmod +x llvm.sh
          sudo ./llvm.sh 21

      - name: Install libc++
        run: |
          sudo apt-get update
          sudo apt-get install -y libc++-21-dev libc++abi-21-dev

      - name: Verify toolchain
        run: |
          cmake --version
          clang++ --version
          clang-format --version
          clang-tidy --version
          find / -name std.cppm 2>/dev/null | head -n 5
          
      - name: Configure
        run: |
          cmake --preset=clang-debug

      - name: clang-format check
        run: |
          cmake --build --preset=clang-debug --target=format-check

      - name: Build
        run: |
          cmake --build --preset=clang-debug

      - name: clang-tidy
        run: |
          cmake --build --preset=clang-debug --target=tidy



