name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  clang-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get CMake 4.1.2
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 4.1.2

      - name: Install Clang 21 and tools
        run: |
          sudo apt update
          sudo apt install -y wget lsb-release software-properties-common
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          sudo apt install clang-format-21 clang-tidy-21
          sudo apt-get install -y libc++-dev libc++abi-dev
          sudo apt install -y ninja-build
          
      - name: Set Clang 21 as default
        run: |
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-21 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-21 100
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-21 65536
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-21 65536
          clang-format --version
          clang-tidy --version

      - name: Install standalone Asio
        run: |
          ASIO_VERSION=1.36.0
          wget -q https://sourceforge.net/projects/asio/files/asio/$ASIO_VERSION%28Stable%29/asio-$ASIO_VERSION.tar.gz/download
          tar xf asio-$ASIO_VERSION.tar.gz
          sudo cp -r asio-$ASIO_VERSION/asio/include/asio /usr/local/include/

      - name: Configure
        run: |
          cmake --preset clang-debug

      - name: clang-format check
        run: |
          cmake --build --preset clang-debug --target format-check

      - name: Build
        run: |
          cmake --build --preset clang-debug

      - name: clang-tidy
        run: |
          cmake --build --preset clang-debug --target tidy
