name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  clang-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get CMake 4.1.2
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 4.1.2

      - name: Install Clang 21 and tools
        run: |
          sudo apt update
          sudo apt install -y wget lsb-release software-properties-common
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          sudo apt install clang-format-21 clang-tidy-21
          sudo apt-get install -y libc++-dev libc++abi-dev
          sudo apt install -y ninja-build
          
      - name: Set Clang 21 as default
        run: |
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-21 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-21 100
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-21 65536
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-21 65536
          clang-format --version
          clang-tidy --version
          
      - name: Build and Install libc++21
        run: |
          set -e

          # Variables
          LLVM_VERSION=21.1.8
          LIBCXX_DIR=$HOME/libcxx-21
          INSTALL_DIR=/usr/local/llvm-21

          # Install dependencies
          sudo apt-get update
          # sudo apt-get install -y cmake ninja-build git build-essential python3

          # Clone LLVM project
          git clone --depth 1 --branch llvmorg-$LLVM_VERSION https://github.com/llvm/llvm-project.git $LIBCXX_DIR

          # Create build dir
          mkdir -p $LIBCXX_DIR/build && cd $LIBCXX_DIR/build

          # Build libc++ and libc++abi only
          cmake -G Ninja ../llvm \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_PROJECTS="libcxx;libcxxabi" \
            -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR \
            -DLLVM_ENABLE_RTTI=ON \
            -DLLVM_TARGETS_TO_BUILD="X86"
          ninja cxx cxxabi
          sudo ninja install-cxx install-cxxabi

          # Set environment variables for Clang to find this libc++
          echo "export PATH=$INSTALL_DIR/bin:\$PATH" >> $GITHUB_ENV
          echo "export CPLUS_INCLUDE_PATH=$INSTALL_DIR/include/c++/v1:\$CPLUS_INCLUDE_PATH" >> $GITHUB_ENV
          echo "export LIBRARY_PATH=$INSTALL_DIR/lib:\$LIBRARY_PATH" >> $GITHUB_ENV
          echo "export LD_LIBRARY_PATH=$INSTALL_DIR/lib:\$LD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Install Asio
        run: |
          git clone --depth=1 --branch asio-1-36-0 https://github.com/chriskohlhoff/asio.git
          sudo cp -r asio/asio/include/* /usr/local/include/

      - name: Configure
        run: |
          cmake --preset clang-debug

      - name: clang-format check
        run: |
          cmake --build --preset clang-debug --target format-check

      - name: Build
        run: |
          cmake --build --preset clang-debug

      - name: clang-tidy
        run: |
          cmake --build --preset clang-debug --target tidy
