name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch: 
  
jobs:
  clang-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: llvm-21
          cmake: 4.1.2
          clang-format: 21
          clang-tidy: 21
          ninja: true

      - name: Set Clang 21 as default
        run: |
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-21 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-21 100
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-21 100
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-21 100
          clang-format --version
          clang-tidy --version

      - name: Configure
        run: |
          cmake --preset clang-debug

      - name: clang-format check
        run: |
          cmake --build --preset clang-debug --target format-check

      - name: Build
        run: |
          cmake --build --preset clang-debug

      - name: clang-tidy
        run: |
          cmake --build --preset clang-debug --target tidy





