name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch: 
  
jobs:
  clang-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install Clang 21 and tools
        run: |
          sudo apt update
          sudo apt install -y wget lsb-release software-properties-common
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          sudo apt-get install -y libc++-dev libc++abi-dev

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: llvm-21
          clang-format: 21
          clang-tidy: 21
          ninja: true

      - name: Get CMake 4.1.2
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: 4.1.2

      - name: Configure
        run: |
          cmake --preset=clang-debug

      - name: clang-format check
        run: |
          cmake --build --preset=clang-debug --target=format-check

      - name: Build
        run: |
          cmake --build --preset=clang-debug

      - name: clang-tidy
        run: |
          cmake --build --preset=clang-debug --target=tidy







